---
deployment:
  tasks:
    # 1. Establecer la ruta de despliegue
    - export DEPLOYPATH=/home/quoterides/public_html/

    # 2. Mover los archivos al directorio de despliegue
    - /bin/cp -R * $DEPLOYPATH

    # 3. Instalar dependencias de Composer
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader

    # 4. Configurar permisos para almacenamiento y cachés
    - /bin/chmod -R 775 $DEPLOYPATH/storage
    - /bin/chmod -R 775 $DEPLOYPATH/bootstrap/cache

    # 5. Generar claves y cachésx
    - php artisan key:generate
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
