---
deployment:
  tasks:
    # 1. Definir ruta de despliegue
    - export DEPLOYPATH=/home/quoterides/public_html/apistaging.quoterides.com
    
    # 2. Copiar todos los archivos ignorando .git
    - /bin/cp -R * $DEPLOYPATH
    
    # 3. Entrar al directorio y ejecutar comandos
    - cd $DEPLOYPATH && /usr/local/bin/composer install --no-dev
    - cd $DEPLOYPATH && /usr/local/bin/npm install
    - cd $DEPLOYPATH && /usr/local/bin/npm run build
    
    # 4. Configurar permisos
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chmod -R 755 $DEPLOYPATH/bootstrap/cache
    
    # 5. Comandos de Laravel
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache